import 'package:flutter/material.dart';

import 'package:easy_localization/easy_localization.dart';

import 'package:doctor/theme/theme_notifier.dart';
import 'package:flutter/src/foundation/change_notifier.dart';



class Settingspage extends StatelessWidget {

  const Settingspage({super.key});



    @override

      Widget build(BuildContext context, ValueListenable<ThemeMode> themeNotifier) {

          return Scaffold(

                appBar: AppBar(

                        title: Text(tr('settings')),

                              ),

                                    body: ListView(

                                            children: [

                                                      /// 🌙 Dark / Light Theme

                                                                ValueListenableBuilder<ThemeMode>(

                                                                            valueListenable: themeNotifier,

                                                                                        builder: (_, mode, __) {

                                                                                                      return SwitchListTile(

                                                                                                                      title: Text(tr('dark mode')),

                                                                                                                                      subtitle: Text(tr('dark_mode_sub')),

                                                                                                                                                      value: mode == ThemeMode.dark,

                                                                                                                                                                      onChanged: (value) {

                                                                                                                                                                                        themeNotifier.value =

                                                                                                                                                                                                              value ? ThemeMode.dark : ThemeMode.light;

                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                  ),



                                                                                                                                                                                                                                                                            const Divider(),



                                                                                                                                                                                                                                                                                      /// 🌍 Language

                                                                                                                                                                                                                                                                                                ListTile(

                                                                                                                                                                                                                                                                                                            leading: const Icon(Icons.language),

                                                                                                                                                                                                                                                                                                                        title: Text(tr('language')),

                                                                                                                                                                                                                                                                                                                                    subtitle: Text(tr('current_language')),

                                                                                                                                                                                                                                                                                                                                                trailing: const Icon(Icons.arrow_forward_ios),

                                                                                                                                                                                                                                                                                                                                                            onTap: () => _showLanguageDialog(context),

                                                                                                                                                                                                                                                                                                                                                                      ),



                                                                                                                                                                                                                                                                                                                                                                                const Divider(),



                                                                                                                                                                                                                                                                                                                                                                                          /// ℹ️ About

                                                                                                                                                                                                                                                                                                                                                                                                    ListTile(

                                                                                                                                                                                                                                                                                                                                                                                                                leading: const Icon(Icons.info_outline),

                                                                                                                                                                                                                                                                                                                                                                                                                            title: Text(tr('about')),

                                                                                                                                                                                                                                                                                                                                                                                                                                        trailing: const Icon(Icons.arrow_forward_ios),

                                                                                                                                                                                                                                                                                                                                                                                                                                                    onTap: () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  showAboutDialog(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  context: context,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  applicationName: tr('app_name'),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  applicationVersion: '1.0.0',

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  applicationLegalese: tr('legalese'),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void _showLanguageDialog(BuildContext context) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                showDialog(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      context: context,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            builder: (_) => AlertDialog(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: Text(tr('select language')),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            content: Column(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mainAxisSize: MainAxisSize.min,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                children: [

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ListTile(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: const Text('English'),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onTap: () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        context.setLocale(const Locale('en'));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Navigator.pop(context);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ListTile(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: const Text('Arabic'),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onTap: () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          context.setLocale(const Locale('ar'));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Navigator.pop(context);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  